version: 2
jobs:
  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3
      

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            echo " ** hello world" # run the `echo` command
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"
            git config --global user.name "$CIRCLE_USERNAME"
            echo "machine github.com login $CIRCLE_USERNAME password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=$CIRCLE_USERNAME yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
#         filters: *filter-only-master
